STICKERS = {
    "welcome": [
        "CAACAgUAAxkBAAEOqihoRXbKM7GnHSpAdtmBYWht_9KetwAC0AEAAt8fchkuFenDj8oThzYE",
        "CAACAgUAAxkBAAEOtBxoTuW2twoQT3O5rxD6PUIkQ2CptQAC4QEAAt8fchnY_ueaOiaM6DYE",
        "CAACAgQAAxkBAAEOtB5oTuXQc4zP8os1xlRzNmVZPpI2gQACsQwAAt1VeVNM_e6mTbxdZjYE",
        "CAACAgUAAxkBAAEOtCBoTuXkCUu0fG3UPGnPM6xf32P-2AAC8QEAAt8fchmbLztCzXRCBTYE",
        "CAACAgIAAxkBAAEOtCJoTuX6lxQjhhDsQrQFlFXLS3bJLQACdF0AAmSIQEtmW6X_FuNIUDYE"
    ]
}