"""crafts_and_items

Revision ID: 36127aa7ebd3
Revises: cadb14fbdc10
Create Date: 2025-06-07 22:06:28.182414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36127aa7ebd3"
down_revision: Union[str, None] = "cadb14fbdc10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("opened_by_id", sa.Uuid(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opened_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crafts",
        sa.Column("result_item_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient1_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient2_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient1_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredient2_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crafts")
    op.drop_table("items")
    # ### end Alembic commands ###
